apiVersion: v1
kind: Pod
metadata:
  name: {{ include "busybox.fullname" . }}
  labels:
    app: {{ include "busybox.name" . }}
spec:
  containers:
  - name: busybox
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    command: [ "sleep", "3600" ]
    volumeMounts:
    - name: storage
      mountPath: {{ .Values.pvc.mountPath }}
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: {{ .Values.pvc.name }}