{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mongodb-allow-graylog
spec:
  podSelector:
    matchLabels:
{{- include "mongodb.selectorLabels" . | nindent 6 }}

  policyTypes:
    - Ingress

  ingress:
    # MongoDB internal traffic
    - from:
        - podSelector:
            matchLabels:
{{- include "mongodb.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}

    # Graylog -> MongoDB
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.allowedNamespace | quote }}
          podSelector:
            matchLabels:
{{- range $key, $value := .Values.networkPolicy.allowedPodLabels }}
              {{ $key }}: {{ $value | quote }}
{{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
{{- end }}
