apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-secret
type: Opaque
data:
  rootUsername: {{ .Values.auth.rootUsername | b64enc | quote }}
  rootPassword: {{ .Values.auth.rootPassword | b64enc | quote }}