apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }} # Must match the serviceName in the StatefulSet
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - port: 27017