apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.secretName" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_PASSWORD: {{ required "global.dbPassword or mysql.password is required" (default .Values.mysql.password .Values.global.dbPassword) | quote }}
  MYSQL_ROOT_PASSWORD: {{ required "mysql.rootPassword is required" .Values.mysql.rootPassword | quote }}
