apiVersion: v2
name: common
description: A library Helm chart for Kubernetes
type: library
version: 1.0.0

icon: https://img.icons8.com/color/48/public--v1.png
maintainers:
- email: larsc@inetpub.dk
  name: lars-c
