---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joomla
  labels:
    app: joomla
spec:
  selector:
    matchLabels:
      app: joomla
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: joomla
        tier: frontend
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: joomla
        env:
        - name: JOOMLA_DB_HOST
          value: {{ include "joomla.mysql.databaseHost" . }}
        - name: JOOMLA_DB_NAME
          value: {{ .Values.global.dbname }}
        - name: JOOMLA_DB_USER
          value: {{ .Values.global.dbuser }}
        - name: JOOMLA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: joomla-secret
              key: dbpassword
        - name: JOOMLA_SITE_NAME
          value: {{ .Values.joomlaSitename }}
        - name: JOOMLA_ADMIN_USER
          value: {{ .Values.joomlaAdminName }}
        - name: JOOMLA_ADMIN_USERNAME
          value: {{ .Values.joomlaAdminUserame }}
        - name: JOOMLA_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: joomla-secret
              key: joomlaAdminPassword
        - name: JOOMLA_EMAIL
          value: {{ default "" .Values.joomlaAdminEmail }}
        ports:
        - containerPort: {{ .Values.service.port }}
          name: joomla
        volumeMounts:
        - name: joomla-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: joomla-persistent-storage
        persistentVolumeClaim:
          claimName: joomla-pv-claim