---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joomla
  labels:
    app: joomla
spec:
  selector:
    matchLabels:
      app: joomla
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: joomla
        tier: frontend
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: joomla
        env:
        - name: JOOMLA_DB_HOST
          value: {{ include "common.dbhostname" . }}
        - name: JOOMLA_DB_NAME
          value: {{ include "common.dbname" . }}
        - name: JOOMLA_DB_USER
          value: {{ include "common.global.dbuser" . }}
        - name: JOOMLA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: joomla-secret
              key: dbpassword
        ports:
        - containerPort: {{ include "joomla.service.port" . }}
          name: joomla
        {{- if .Values.startupProbe.enabled }}
        startupProbe:
          httpGet:
            path: /index.php
            port: joomla
          initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.startupProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
          successThreshold: {{ .Values.startupProbe.successThreshold }}
          failureThreshold: {{ .Values.startupProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
            tcpSocket:
              port: joomla
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
            httpGet:
              path: /index.php
              port: joomla
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
        {{- end }}
        volumeMounts:
        - name: joomla-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: joomla-persistent-storage
        persistentVolumeClaim:
          claimName: joomla-pv-claim
      {{- if .Values.affinity.enabled }}
      affinity:
        nodeAffinity:
          {{- if and .Values.affinity.preferred (not .Values.affinity.required) }}
          preferredDuringSchedulingIgnoredDuringExecution:
          {{- range .Values.affinity.preferredDuringSchedulingIgnoredDuringExecution }}
          - weight: {{ .weight }}
            preference:
              matchExpressions:
              - key: {{ .key }}
                operator: {{ .operator }}
                values:
                {{- range .values }}
                - {{ . }}
                {{- end }}
          {{- end }}
          {{- else if and .Values.affinity.required (not .Values.affinity.preferred) }}
          requiredDuringSchedulingIgnoredDuringExecution:
          {{- range .Values.affinity.requiredDuringSchedulingIgnoredDuringExecution }}
            nodeSelectorTerms:
              - matchExpressions:
                - key: {{ .key }}
                  operator: {{ .operator }}
                  values:
                  {{- range .values }}
                  - {{ . }}
                  {{- end }}
          {{- end }}
          {{- else }}
          preferredDuringSchedulingIgnoredDuringExecution:
            {{- range .Values.affinity.preferredDuringSchedulingIgnoredDuringExecution }}
            - weight: {{ .weight }}
              preference:
                matchExpressions:
                - key: {{ .key }}
                  operator: {{ .operator }}
                  values:
                  {{- range .values }}
                  - {{ . }}
                  {{- end }}
            {{- end }}
          {{- end }}
      {{- end }}