---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joomla
  labels:
    app: joomla
spec:
  selector:
    matchLabels:
      app: joomla
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: joomla
        tier: frontend
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: joomla
        env:
        - name: JOOMLA_DB_HOST
          value: {{ include "common.db.hostname" . }}
        - name: JOOMLA_DB_NAME
          value: {{ include "common.dbname" . }}
        - name: JOOMLA_DATABASE_PORT_NUMBER
          value: {{ include "common.joomlaDbPort" . }}
        - name: JOOMLA_DB_USER
          value: {{ include "common.dbuser" . }}
        - name: JOOMLA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: joomla-secret
              key: dbpassword
        ports:
        - containerPort: 80
          name: joomla
        {{- if .Values.startupProbe.enabled }}
        startupProbe:
          httpGet:
            path: /index.php
            port: joomla
          initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.startupProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
          successThreshold: {{ .Values.startupProbe.successThreshold }}
          failureThreshold: {{ .Values.startupProbe.failureThreshold }}
        {{- end }}
        volumeMounts:
        - name: joomla-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: joomla-persistent-storage
        persistentVolumeClaim:
          claimName: joomla-pv-claim