---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: joomla-pv-claim
  labels:
    app: joomla
spec:
  storageClassName: {{ .Values.persistence.storageClass }} 
  accessModes:
    - {{ .Values.persistence.accessModes }} 
  resources:
    requests:
      storage: {{ .Values.persistence.size }} 