---
apiVersion: v1
kind: Secret
metadata:
  name: joomla-secret
type: Opaque
data:
  {{ if .Values.joomlaPassword }}
  joomla-password: {{ default "" .Values.joomlaPassword | b64enc | quote }}
  {{ else }}
  joomla-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  smtp-password: {{ default "" .Values.smtpPassword | b64enc | quote }}
  