---
apiVersion: v1
kind: Secret
metadata:
  name: joomla-secret
type: Opaque
data:
  {{- if .Values.joomlaAdminPassword -}}
  joomlaAdminPassword: {{- default "" .Values.joomlaAdminPassword | b64enc | quote -}}
  {{ else }}
  joomlaAdminPassword: {{- randAlphaNum 10 | b64enc | quote -}}
  {{ end }}
  {{- if .Values.global.dbpassword -}}
  dbpassword: {{- .Values.global.dbpassword | b64enc | quote -}}
  {{ else }}
  dbpassword: {{- randAlphaNum 16 | b64enc | quote -}}
  {{ end }}  
  smtp-password: {{- default "" .Values.smtpPassword | b64enc | quote -}}
  