apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-restore-pv
  labels:
    role: mongo-restore
spec:
  capacity: { storage: 1Gi }
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}