global:
  dbname: "joomla_db"
  dbuser: "joomla"
  dbpassword: "dbpassword"
  joomlaDbHost: "joomla-mysql"
  joomlaDbPort: "3306"
service:
  loadBalancerIP: "192.168.1.76"
affinity:
  enabled: false
  preferred: true
  required: false
  preferredDuringSchedulingIgnoredDuringExecution:
  - weight: 1
    key: color
    operator: In
    values:
      - pink
  - weight: 50
    key: color
    operator: In
    values:
      - green
mysql:
  auth:
    rootdbpassword: "bxJK8Q1wd9ZFeDO8bOKbQ9CN"
  persistence:
    storageClass: "local-path"
    accessModes: "ReadWriteOnce"
    size: 2Gi
