global:
  dbname: "joomla_db"
  dbuser: "joomla"
  dbpassword: "dbpassword"
  joomlaDbHost: "joomla-mysql"
  joomlaDbPort: "3306"
image:
  repository: joomla
  tag: "php8.3-apache"
  pullPolicy: IfNotPresent
persistence:
  enabled: "true"
  storageClass: "local-path"
  accessModes: "ReadWriteOnce"
  size: 1Gi
service:
  type: LoadBalancer
  port: 80
  loadBalancerIP: "192.168.1.56"
resources:
  requests:
    cpu: 100m
    memory: 128Mi
startupProbe:
  enabled: false
  initialDelaySeconds: 600
  periodSeconds: 20
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 3
livenessProbe:
  enabled: false
  initialDelaySeconds: 600
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: false
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 6
  successThreshold: 1
tolerationsEnabled: true
tolerations:
  - key: "key1"
    operator: "Equal"
    value: "gray"
    effect: "NoSchedule"
  - key: "key1"
    operator: "Equal"
    value: "orange"
    effect: "NoSchedule"
affinity:
  enabled: true
  preferred: true
  required: false
  preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 10
      key: color
      operator: In
      values:
        - pink
    - weight: 20
      key: color
      operator: In
      values:
        - green
  requiredDuringSchedulingIgnoredDuringExecution:
    - key: color
      operator: In
      values:
        - green
mysql:
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  auth:
    rootdbpassword: "bxJK8Q1wd9ZFeDO8bOKbQ9CN"
  timezone: "Europe/Copenhagen"
  persistence:
    storageClass: "local-path"
    accessModes: "ReadWriteOnce"
    size: 2Gi
  tolerationsEnabled: true
  tolerations:
    - key: "key1"
      operator: "Equal"
      value: "gray"
      effect: "NoSchedule"
    - key: "key1"
      operator: "Equal"
      value: "orange"
      effect: "NoSchedule"
  affinity:
    enabled: true
    preferred: true
    required: false
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        key: color
        operator: In
        values:
          - pink
      - weight: 5
        key: color
        operator: In
        values:
          - green
    requiredDuringSchedulingIgnoredDuringExecution:
      - key: color
        operator: In
        values:
          - green