global:
  ## JOOMLA_DB_NAME
  dbname: "joomla_db"
  ## 
  dbuser: "joomla"
  ##
  ## JOOMLA_DB_PASSWORD / MYSQL_ROOT_PASSWORD
  dbpassword: "dbpassword"
  ##
  ## JOOMLA_DB_HOST
  joomlaDbHost: "joomla-mysql"
  ## JOOMLA_DATABASE_PORT_NUMBER MYSQL_TCP_PORT
  joomlaDbPort: "3306"
service:
  ## loadBalancerIP for the Joomla Service
  ##
  loadBalancerIP: "192.168.1.76"