apiVersion: v2
name: busybox
description: A test chart for busybox
version: 0.1.0
appVersion: "1.37.0"
type: application

icon: https://img.icons8.com/color/48/public--v1.png
maintainers:
- email: larsc@inetpub.dk
  name: lars-c


