# Default values for mongodb-restore.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: mongo
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "8.0.12"

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This is for setting up the mongodb authentication more information can be found here: https://hub.docker.com/_/mongo
auth:
  rootUsername: "admin"
  rootPassword: "SecurePassword123"

# This is the host and port for the restore
mongo:
  # List of host:port for your *target* replica set
  hosts:
    - mongodb-0.mongo-service.dok1.svc.cluster.local:27017
    - mongodb-0.mongo-service.dok1.svc.cluster.local:27017
    - mongodb-0.mongo-service.dok1.svc.cluster.local:27017
  replicaSet: rs0
  authSource: admin

# Setting for restore type
restore:
  # Set true only if your dumps were taken with --oplog (full dump)
  useOplogReplay: true  

# This is the Job configuration more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/job/
job:
  ttlSecondsAfterFinished: 900
  backoffLimit: 0
  activeDeadlineSeconds: 1800  # optional

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 80

# Optional resources
resources:
  requests: { cpu: "100m", memory: "256Mi" }
  limits:   { cpu: "1",    memory: "1Gi" }

# NFS server configuration
nfs:
  server: 192.168.1.25
  path: /var/nfs/backup