apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-backups-pv
  labels:
    role: mongo-backup
spec:
  capacity: { storage: {{ .Values.persistence.size }} }
  accessModes: [{{ .Values.persistence.accessMode }}]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}