apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-backups-pv
  labels:
    role: mongo-backup
spec:
  capacity: { storage: {{ .Values.persistence.size }} }
  accessModes: [{{ .Values.persistence.accessMode }}]
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers={{ .Values.mountOptions.nfsvers }}
    {{- if .Values.mountOptions.enable_rsize }}
    - {{ printf "rsize=%d" (int (.Values.mountOptions.rsize)) }}
    {{- end }}
    {{- if .Values.mountOptions.enable_wsize }}
    - {{ printf "print=%d" (int (.Values.mountOptions.wsize)) }}
    {{- end }}
    {{- if .Values.mountOptions.hard }}
    - hard
    {{- end }}
    - timeo={{ .Values.mountOptions.timeo }}  
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}