---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joomla-mysql
  labels:
    app: joomla
spec:
  selector:
    matchLabels:
      app: joomla
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: joomla
        tier: mysql
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: mysql
        env:
        - name: MYSQL_HOST
          value: {{ include "common.dbhostname" . }}
        - name: MYSQL_DATABASE
          value: {{ include "common.dbname" . }}
        - name: MYSQL_TCP_PORT
          value: {{ include "common.joomlaEnvDbPort" . }}
        - name: MYSQL_USER
          value: {{ include "common.global.dbuser" . }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: dbpassword
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: rootdbpassword
        - name: TZ
          value: {{ .Values.timezone | quote }}
        ports:
        - containerPort: {{ include "common.joomlaDbPort" . }}
          name: mysql
        volumeMounts:
        - name: joomla-mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes: 
      - name: joomla-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: joomla-mysql-pv-claim
      {{- if .Values.affinity.enabled }}
      affinity:
        nodeAffinity:
          {{- if and .Values.affinity.preferred (not .Values.affinity.required) }}
          preferredDuringSchedulingIgnoredDuringExecution:
            {{- range .Values.affinity.preferredDuringSchedulingIgnoredDuringExecution }}
            - weight: {{ .weight }}
              preference:
                matchExpressions:
                - key: {{ .key }}
                  operator: {{ .operator }}
                  values:
                  {{- range .values }}
                  - {{ . }}
                  {{- end }}
            {{- end }}            
          {{- else if and .Values.affinity.required (not .Values.affinity.preferred) }}
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- range .Values.affinity.requiredDuringSchedulingIgnoredDuringExecution }}
              nodeSelectorTerms:
                - matchExpressions:
                  - key: {{ .key }}
                    operator: {{ .operator }}
                    values:
                    {{- range .values }}
                    - {{ . }}
                    {{- end }}
            {{- end }}            
          {{- else }}
          preferredDuringSchedulingIgnoredDuringExecution:
            {{- range .Values.affinity.preferredDuringSchedulingIgnoredDuringExecution }}
            - weight: {{ .weight }}
              preference:
                matchExpressions:
                - key: {{ .key }}
                  operator: {{ .operator }}
                  values:
                  {{- range .values }}
                  - {{ . }}
                  {{- end }}
            {{- end }}            
          {{- end }}
      {{- end }}

          
