---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joomla-mysql
  labels:
    app: joomla
spec:
  selector:
    matchLabels:
      app: joomla
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: joomla
        tier: mysql
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: mysql
        env:
        - name: MYSQL_HOST
          value: {{ include "common.db.hostname" . }}
        - name: MYSQL_DATABASE
          value: {{ include "common.dbname" . }}
        - name: MYSQL_TCP_PORT
          value: {{ include "common.joomlaDbPort" . }}
        - name: MYSQL_USER
          value: {{ include "common.dbuser" . }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: dbpassword
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: rootdbpassword
        - name: TZ
          value: {{ .Values.timezone | quote }}
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: joomla-mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes: 
      - name: joomla-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: joomla-mysql-pv-claim
