---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: joomla-mysql-pv-claim
  labels:
    app: joomla
spec:
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  accessModes:
    - {{ .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}