---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  dbpassword: "{{ include "common.global.dbpassword" . }}"
  rootdbpassword: "{{ include "common.mysql.rootpassword" . }}"