---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  {{ if .Values.global.dbpassword}}
  dbpassword: {{- .Values.global.dbpassword | b64enc | quote -}}
  {{ else }}
  dbpassword: {{- randAlphaNum 16 | b64enc | quote -}}
  {{ end }}